spring:
  datasource:
    url: jdbc:mysql://ec2-13-125-145-185.ap-northeast-2.compute.amazonaws.com:3306/k8stest?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
server:
  servlet:
    context-path: /api

# 로깅 레벨 설정
logging:
  level:
    root: info


